version: "3"

services:
  app:
    image: fastapi
    env_file: .env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      SECRET_KEY: ${SECRET_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 3
